---
title: "Analysis of public barcode count datasets"
author: "Liyang Fei"
date: |
  Initiate: early 2025 
  
  Last update: `r format(Sys.Date(), '%Y-%m-%d')`
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

# Project aim

This project gathered several public barcode count datasets and analyzed them using the `barbieQ` package

# Analyses in the barbieQ paper

[barbieQ preprint on bioRxiv](https://www.biorxiv.org/content/10.1101/2025.09.11.675529v1)

[barbieQ R package on GitHub](https://github.com/Oshlack/barbieQ)

[barbieQ R package on Bioconductor](https://www.bioconductor.org/packages/release/bioc/html/barbieQ.html)

|**Figure**|**Content** |
|---|------|
|[Figure 1](https://raw.githubusercontent.com/Oshlack/barbieQ-paper-analysis/filtered/output/barbieQ_figure1.drawio.png) |Package flowchart |
|[Figure 2](barbieQ_paper_Figure2.html) |Preprocessing Monkey HSPC data |
|[Figure S1 AML](barbieQ_paper_FigureS1_AML.html) |Preprocessing AML data |
|[Figure S1 HSPC xeno](barbieQ_paper_FigureS1_xenoHSPC.html) |Preprocessing HSPC xenograft data |
|[Figure S1 Mixture](barbieQ_paper_FigureS1_Mixture.html) |Preprocessing Mixture data |
|[Figure 3 and Figure S3](barbieQ_paper_Figure3.html) |Assessing Type I error rate and power of statistical tests using Mixture data|
|[Figure S2 AML](barbieQ_paper_FigureS2_AML.html) |Assessing Type I error rate using AML data |
|[Figure S2 HSPC xeno](barbieQ_paper_FigureS2_xenoHSPC.html) |Assessing Type I error rate using HSPC xenograft data |
|[Figure 4](barbieQ_paper_Figure4.html) |Case study using Monkey HSPC data|
| | |

# Datasets

## HSPC xenograft data [Access](../data/BelderbosME/)

Public data from [a study of engraftment tracking of human umbilical cord blood HSPC xenotransplanted into mice](https://doi.org/10.1016/j.bbmt.2019.08.026). The data were analysed in the [barcodetrackR publication](https://doi.org/10.1038/s43588-021-00057-4) and made available via the compatible barcodetrackRData repository on [GitHub](https://github.com/dunbarlabNIH/barcodetrackRData/tree/main/datasets/BelderbosME_etal). 

In this study, human cord blood HSPC cells from 20 individual donors were isolated and barcoded at the DNA level respectively. Sets of starting clones from different donors were transplanted into different mice (n = 30), each donor in line with 1 or 2 recipient mice. For each mouse, progeny cells were collected from peripheral blood at multiple time points, as well as from various tissues. From each collection, cells were sorted into different cell types forming individual samples, with unsorted cells also retained. Herein, we used data of recipient mice with sufficiently engrafted HSPC clones, containing 10,149 barcodes across 8 donors, with 199 samples, under the described conditions. 
 
## AML data [Access](../data/bartools_dose_escalation/)

Publicly available data from a study of acute myeloid leukaemia (AML) clones, investigating the heterogeneity in their response to various therapeutic drugs in vitro, which was originally analysed and introduced with [bartools](https://zenodo.org/doi/10.5281/zenodo.10896642). Briefly, AML cells were barcoded at the DNA level using the SPLINTR system, recognized as individual clones, and their population was expanded under exposure to different drugs (Arac, IBET), at various doses and DMSO as a negative control. Samples were collected from each treatment condition at a series of time points. This barcode count matrix contains 1,811 barcodes, across 41 samples, under the described conditions.
 
## Mixture data [Access](../data/DEBRA/)

[Original publication](https://doi.org/10.15252/msb.20199195)

Dataset generated to simulate both true and null changes in barcode abundance by mixing cells from two barcoded samples. Cells from each cell line were divided into two pools (Pool1 and Pool2), each incorporating distinct clonal tracking barcodes into their DNA, ensuring no overlap  between pools. Cells in each pool were counted and mixed in an equal ratio to produce a mixed pool. Twelve baseline samples were sampled from the mixed pool at various sizes. Twenty-four perturbed samples were generated by sampling a certain number of cells from the mixed pool and adding a certain ratio of cells from Pool1, with 2 replicates in each case. This dataset contains 3998 barcodes, across 36 samples as described, as well as two reference samples representing the unmixed Pool1 and Pool2 barcode counts.
 
## Monkey HSPC data [Access](../data/WuC/)

A subset of publicly available data from [a study on monkey hematopoietic stem and progenitor cell (HSPC) clonal expansion in vivo using barcoding technique](https://www.science.org/doi/10.1126/sciimmunol.aat9781). The monkey HSPC data have been analysed using the barcodetrackR package and made available via the compatible barcodetrackRData repository on [GitHub](https://github.com/dunbarlabNIH/barcodetrackRData/tree/main/datasets/WuC_etal). Herein, we used data from monkey "ZG66"  including 16,603 barcodes across all samples, where we further selected 30 samples to be used here.

Briefly, unique barcodes were initially integrated into the DNA of HSPCs and subsequently passed to progeny cells. At a series of time points, progeny cells were collected from blood and sorted into various cell types, including T cells, B cells, granulocytes (Gr), and natural killer (NK) cells for NKCD56+CD16- and NKCD56-CD16+ subtypes. Barcode counts across different cell types were used to interpret the patterns of HSPC differentiation. The original study focused on identifying barcodes (clones) with higher abundance in NKCD56-CD16+ samples compared to other cell type samples.


```{r eval=FALSE, include=FALSE}
# Explore filtering strategies by comparing filtered and unfiltered data regarding statistical test results on barcode differential proportion. [filtering_explore_alter](WuC/filtering_explore_alter.html)
# 
# When selecting NK-biased clones, compare the performance of barbieQ and the paper's strategy based on the paper's validation method. [compare_original_analysis](WuC/compare_original_analysis.html)
```

